### ISSUE TITLE
关于init_register_ida_addr

### ISSUE THREAD

**Issue by athlan20** [4ch12dy/XIL2CppDumper#1]
IL2CppBinParser.cpp中的assert(init_register_ida_addr);老是过不去,值是0,麻烦问下我看上面代码
if ((metadataVersion == 24) && arm_is_ldr_literal(insn_1) && arm_is_mov_imm(insn_2) && arm_is_ldr_literal(insn_3) && arm_is_mov_imm(insn_4) && arm_is_add_r(insn_5) && arm_is_add_r(insn_6))
应该是在检测某些个arm指令对吧,这主要是什么意思

**Comment by 4ch12dy** [comment]
这是在so里面通过特征指令找il2cpp的两张表地址，没找到的原因有两种：一是因为il2cpp的版本不对，目前还不支持；二是可能so加壳了的原因。
另外32位目前的so我预编译的并不支持，只编译了64位的Android/iOS版本。对64位的支持也好一点，测试的话我在resource目录下放置了iOS的metadata文件和可执行文件作为测试。

**Comment by athlan20** [comment]
哇,那么快回复了,多谢啊,我再去消化下大佬的程序,多谢啦
